repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: trailing-whitespace
-   repo: https://github.com/pycqa/pydocstyle
    rev: 5.0.2
    hooks:
    -   id: pydocstyle
-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/bandit
    rev: 1.6.2
    hooks:
    - id: bandit
